@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@baseurl = http://{{host}}

### create a new user account
POST {{baseurl}}/create_account HTTP/1.1
Content-Type: application/json

{
  "username": "ronniemyers",
  "password": "$$halloween9"
}

### authenticate an existing user
POST {{baseurl}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "ronniemyers",
    "password": "$$halloween9"
}

### refresh a non-expired token
POST http://localhost:5000/refresh_token HTTP/1.1
Content-Type: application/json

{
  "jwt_token": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkZXYxMC11c2Vycy1hcGkiLCJzdWIiOiJqb2huQHNtaXRoLmNvbSIsImlkIjoiOTgzZjEyMjQtYWY0Zi0xMWViLTgzNjgtMDI0MmFjMTEwMDAyIiwicm9sZXMiOiJBRE1JTiIsImV4cCI6MTYyMDQyODA5NX0.HrFalpusNo88aNCJXYtrGp5gOGMvinEQXI1QPstw-2M"
}
