### create a new user account

#"id": "c31d34c4-b69a-4d58-ae6b-be4f16c72742"

POST http://localhost:5000/create_account HTTP/1.1
Content-Type: application/json

{
  "username": "ronniemyers",
  "password": "$$halloween9"
}

### authenticate an existing user
POST http://localhost:5000/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

### refresh a non-expired token
POST http://localhost:5000/refresh_token HTTP/1.1
Content-Type: application/json

{
  "jwt_token": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkZXYxMC11c2Vycy1hcGkiLCJzdWIiOiJqb2huQHNtaXRoLmNvbSIsImlkIjoiOTgzZjEyMjQtYWY0Zi0xMWViLTgzNjgtMDI0MmFjMTEwMDAyIiwicm9sZXMiOiJBRE1JTiIsImV4cCI6MTYyMDQyODA5NX0.HrFalpusNo88aNCJXYtrGp5gOGMvinEQXI1QPstw-2M"
}
